
name: Fusion
version: 2024.1.1
slug: ha_fusion
description: A modern, easy-to-use and performant custom Home Assistant dashboard
url: https://github.com/matt8707/addon-ha-fusion
init: false
arch:
  - aarch64
  - amd64
apparmor: true
ingress: true
ingress_stream: true
panel_icon: mdi:atom
image: matt8707/addon-ha-fusion-{arch}
